"""
Category Classifier — Owner: Arpan Chatterjee
TF-IDF + Random Forest pipeline for receipt category classification.
Status: placeholder — real prediction requires trained .pkl files (see Notebook 02).
Target: F1 (weighted) > 0.80 across Grocery / Food & Beverage / General Retail.
"""

import joblib
import os

# ── MODEL FILE PATHS ───────────────────────────────────────────
# Both files are generated by Notebook 02 and must not be committed to git (large binaries)
MODEL_PATH = os.path.join(os.path.dirname(__file__), "models", "classifier.pkl")
VECTORIZER_PATH = os.path.join(os.path.dirname(__file__), "models", "tfidf.pkl")


# ── TRAINING ENTRY POINT ───────────────────────────────────────
# Called from Notebook 02 to fit and save the TF-IDF + Random Forest pipeline
def train(X_train, y_train):
    """Fits the classifier and saves model + vectorizer to models/."""
    pass  # TODO (Arpan): fit pipeline and joblib.dump to MODEL_PATH / VECTORIZER_PATH


# ── INFERENCE ENTRY POINT ──────────────────────────────────────
# Called by /ml/classify route after every OCR extraction
def predict(items_text: str, merchant: str = "") -> dict:
    """Classify receipt text into a spend category."""
    if not os.path.exists(MODEL_PATH) or not os.path.exists(VECTORIZER_PATH):
        return {"category": "Unknown", "confidence": 0.0, "model_ready": False}

    try:
        vectorizer = joblib.load(VECTORIZER_PATH)
        model = joblib.load(MODEL_PATH)
        text = f"{merchant} {items_text}".strip()
        vec = vectorizer.transform([text])
        category = model.predict(vec)[0]
        confidence = float(model.predict_proba(vec).max())
        return {"category": category, "confidence": round(confidence, 4), "model_ready": True}
    except Exception as exc:
        return {"category": "Unknown", "confidence": 0.0, "model_ready": False, "error": str(exc)}
