"""
Category Classifier — Owner: Arpan Chatterjee · serving path: Ashfaaq KT
TF-IDF + Random Forest pipeline for receipt spend-category classification.

LIVE. Trained by Notebook 02 (and mirrored by train_classifier.py, which refits
in the serving environment so sklearn versions match): Random Forest beat Linear
SVM and Logistic Regression, test macro-F1 0.942 / accuracy 0.944 across
Supermarket / Grocery · Food & Beverage · General Retail.

server.js keeps this prediction only when confidence >= 0.45 and otherwise falls
back to the category Gemini read off the receipt.

The two .pkl files are gitignored — see fetch_models.py, or docs/SETUP.md §6 to
rebuild them locally.
"""

import os

import joblib

# ── MODEL FILE PATHS ───────────────────────────────────────────
# Both files are generated by Notebook 02 and must not be committed to git (large binaries)
MODEL_PATH = os.path.join(os.path.dirname(__file__), "models", "classifier.pkl")
VECTORIZER_PATH = os.path.join(os.path.dirname(__file__), "models", "tfidf.pkl")

# Loaded once per process. classifier.pkl is 8.4 MB, and reloading both files on
# every call cost 84 ms against 49 ms of actual inference — roughly 35 ms burned
# per receipt re-reading a pickle that never changes. Every other model in this
# service (fraud.py, anomaly.py, recommend.py) already caches this way.
_vectorizer = None
_model = None
_load_attempted = False


def _load():
    """Returns (vectorizer, model), or (None, None) if they are unavailable."""
    global _vectorizer, _model, _load_attempted

    if _load_attempted:
        return _vectorizer, _model
    _load_attempted = True

    if not os.path.exists(MODEL_PATH) or not os.path.exists(VECTORIZER_PATH):
        print("classifier.py: models/ has no classifier.pkl + tfidf.pkl — "
              "category falls back to Gemini's reading")
        return None, None

    try:
        _vectorizer = joblib.load(VECTORIZER_PATH)
        _model = joblib.load(MODEL_PATH)
    except Exception as exc:
        # Cached as a failure on purpose: a corrupt pickle would otherwise be
        # retried on every upload, paying the load cost each time to fail again.
        print(f"classifier.py: failed to load model ({exc}) — using Gemini's category")
        _vectorizer, _model = None, None

    return _vectorizer, _model


# ── INFERENCE ENTRY POINT ──────────────────────────────────────
# Called by /ml/classify route after every OCR extraction
def predict(items_text: str, merchant: str = "") -> dict:
    """Classify receipt text into a spend category."""
    vectorizer, model = _load()
    if vectorizer is None or model is None:
        return {"category": "Unknown", "confidence": 0.0, "model_ready": False}

    try:
        text = f"{merchant} {items_text}".strip()
        vec = vectorizer.transform([text])
        category = model.predict(vec)[0]
        confidence = float(model.predict_proba(vec).max())
        return {"category": category, "confidence": round(confidence, 4), "model_ready": True}
    except Exception as exc:
        return {"category": "Unknown", "confidence": 0.0, "model_ready": False, "error": str(exc)}
